package com.bbva.zic.renapopersons.business.ws.byData;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-08-24T10:52:41.762-05:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", name = "ConsultaCurpDetalleServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.bbva.zic.renapopersons.business.ws.byData.xsd.ObjectFactory.class})
public interface ConsultaCurpDetalleServicePortType {

    @WebResult(name = "return", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
    @Action(input = "urn:consultarCurpDetalle", output = "urn:consultarCurpDetalleResponse")
    @RequestWrapper(localName = "consultarCurpDetalle", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.ConsultarCurpDetalle")
    @WebMethod(action = "urn:consultarCurpDetalle")
    @ResponseWrapper(localName = "consultarCurpDetalleResponse", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.ConsultarCurpDetalleResponse")
    public java.lang.String consultarCurpDetalle(
        @WebParam(name = "datos", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        com.bbva.zic.renapopersons.business.ws.byData.xsd.DatosConsultaDetalles datos
    );

    @Oneway
    @Action(input = "urn:getConfirm")
    @RequestWrapper(localName = "getConfirm", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.GetConfirm")
    @WebMethod(action = "urn:getConfirm")
    public void getConfirm(
        @WebParam(name = "sessionID", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        java.lang.String sessionID,
        @WebParam(name = "Mssg", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        java.lang.String mssg
    );
}
