package com.bbva.zic.renapopersons.business.ws.byCurp;

import javax.jws.Oneway;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.6.10
 * 2015-09-02T14:33:53.375-05:00
 * Generated source version: 2.6.10
 * 
 */
@WebService(targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", name = "ConsultaPorCurpServicePortType")
@XmlSeeAlso({ObjectFactory.class, com.bbva.zic.renapopersons.business.ws.byCurp.xsd.ObjectFactory.class})
public interface ConsultaPorCurpServicePortType {

    @WebResult(name = "return", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
    @Action(input = "urn:consultarPorCurp", output = "urn:consultarPorCurpResponse")
    @RequestWrapper(localName = "consultarPorCurp", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.ConsultarPorCurp")
    @WebMethod(action = "urn:consultarPorCurp")
    @ResponseWrapper(localName = "consultarPorCurpResponse", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.ConsultarPorCurpResponse")
    public java.lang.String consultarPorCurp(
        @WebParam(name = "datos", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        com.bbva.zic.renapopersons.business.ws.byCurp.xsd.DatosConsultaCurp datos
    );

    @Oneway
    @Action(input = "urn:getConfirm")
    @RequestWrapper(localName = "getConfirm", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx", className = "mx.gob.segob.dgti.ecurp.wserv.services.GetConfirm")
    @WebMethod(action = "urn:getConfirm")
    public void getConfirm(
        @WebParam(name = "sessionID", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        java.lang.String sessionID,
        @WebParam(name = "Mssg", targetNamespace = "http://services.wserv.ecurp.dgti.segob.gob.mx")
        java.lang.String mssg
    );
}
