// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM4026_Roo_ToString {
    
    public String FormatoBGM4026.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Con05: ").append(getCon05()).append(", ");
        sb.append("Con06: ").append(getCon06()).append(", ");
        sb.append("Cond23: ").append(getCond23()).append(", ");
        sb.append("Cond24: ").append(getCond24()).append(", ");
        sb.append("Cond31: ").append(getCond31()).append(", ");
        sb.append("Cuotimp: ").append(getCuotimp()).append(", ");
        sb.append("Depto: ").append(getDepto()).append(", ");
        sb.append("Litahoi: ").append(getLitahoi()).append(", ");
        sb.append("Salahoi: ").append(getSalahoi());
        return sb.toString();
    }
    
}
