// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b000;

import java.lang.Integer;
import java.lang.String;

privileged aspect FormatoBGM000_Roo_JavaBean {
    
    public Integer FormatoBGM000.getProduct() {
        return this.product;
    }
    
    public void FormatoBGM000.setProduct(Integer product) {
        this.product = product;
    }
    
    public String FormatoBGM000.getEntcto() {
        return this.entcto;
    }
    
    public void FormatoBGM000.setEntcto(String entcto) {
        this.entcto = entcto;
    }
    
    public String FormatoBGM000.getConcept() {
        return this.concept;
    }
    
    public void FormatoBGM000.setConcept(String concept) {
        this.concept = concept;
    }
    
    public String FormatoBGM000.getPapel() {
        return this.papel;
    }
    
    public void FormatoBGM000.setPapel(String papel) {
        this.papel = papel;
    }
    
    public String FormatoBGM000.getLibre() {
        return this.libre;
    }
    
    public void FormatoBGM000.setLibre(String libre) {
        this.libre = libre;
    }
    
}
