// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;
import java.util.Date;

privileged aspect FormatoBGM4022_Roo_JavaBean {
    
    public Date FormatoBGM4022.getFecdes() {
        return this.fecdes;
    }
    
    public void FormatoBGM4022.setFecdes(Date fecdes) {
        this.fecdes = fecdes;
    }
    
    public String FormatoBGM4022.getCon01() {
        return this.con01;
    }
    
    public void FormatoBGM4022.setCon01(String con01) {
        this.con01 = con01;
    }
    
    public String FormatoBGM4022.getCccserv() {
        return this.cccserv;
    }
    
    public void FormatoBGM4022.setCccserv(String cccserv) {
        this.cccserv = cccserv;
    }
    
    public String FormatoBGM4022.getCon03() {
        return this.con03;
    }
    
    public void FormatoBGM4022.setCon03(String con03) {
        this.con03 = con03;
    }
    
}
