// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b431;

import java.lang.String;

privileged aspect FormatoBGM4311_Roo_ToString {
    
    public String FormatoBGM4311.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Centro: ").append(getCentro()).append(", ");
        sb.append("Con01: ").append(getCon01()).append(", ");
        sb.append("Cuenta: ").append(getCuenta()).append(", ");
        sb.append("Descdiv: ").append(getDescdiv()).append(", ");
        sb.append("Digitos: ").append(getDigitos()).append(", ");
        sb.append("Dispon: ").append(getDispon()).append(", ");
        sb.append("Divisa: ").append(getDivisa()).append(", ");
        sb.append("Entidad: ").append(getEntidad()).append(", ");
        sb.append("Fecform: ").append(getFecform()).append(", ");
        sb.append("Subtal: ").append(getSubtal());
        return sb.toString();
    }
    
}
