// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b431;

import java.lang.String;

privileged aspect FormatoBGMLI02_Roo_ToString {
    
    public String FormatoBGMLI02.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Indnota: ").append(getIndnota());
        return sb.toString();
    }
    
}
