// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b431;

import java.io.Serializable;

privileged aspect FormatoBGMLI02_Roo_Serializable {
    
    declare parents: FormatoBGMLI02 implements Serializable;
    
    private static final long FormatoBGMLI02.serialVersionUID = 1L;
    
}
