// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM402A_Roo_ToString {
    
    public String FormatoBGM402A.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Ccc: ").append(getCcc()).append(", ");
        sb.append("Cccaso: ").append(getCccaso()).append(", ");
        sb.append("Claveb: ").append(getClaveb()).append(", ");
        sb.append("Con1: ").append(getCon1()).append(", ");
        sb.append("Con10: ").append(getCon10()).append(", ");
        sb.append("Con109: ").append(getCon109()).append(", ");
        sb.append("Con110: ").append(getCon110()).append(", ");
        sb.append("Con111: ").append(getCon111()).append(", ");
        sb.append("Con112: ").append(getCon112()).append(", ");
        sb.append("Con113: ").append(getCon113()).append(", ");
        sb.append("Con114: ").append(getCon114()).append(", ");
        sb.append("Con2: ").append(getCon2()).append(", ");
        sb.append("Con3: ").append(getCon3()).append(", ");
        sb.append("Con4: ").append(getCon4()).append(", ");
        sb.append("Con44: ").append(getCon44()).append(", ");
        sb.append("Con5: ").append(getCon5()).append(", ");
        sb.append("Con6: ").append(getCon6()).append(", ");
        sb.append("Con7: ").append(getCon7()).append(", ");
        sb.append("Con8: ").append(getCon8()).append(", ");
        sb.append("Con9: ").append(getCon9()).append(", ");
        sb.append("Concc: ").append(getConcc()).append(", ");
        sb.append("Conlp: ").append(getConlp()).append(", ");
        sb.append("Consal: ").append(getConsal()).append(", ");
        sb.append("Ctacen: ").append(getCtacen()).append(", ");
        sb.append("Disci: ").append(getDisci()).append(", ");
        sb.append("Disext: ").append(getDisext()).append(", ");
        sb.append("Dispon: ").append(getDispon()).append(", ");
        sb.append("Disrem: ").append(getDisrem()).append(", ");
        sb.append("Divisa: ").append(getDivisa()).append(", ");
        sb.append("Exccaj: ").append(getExccaj()).append(", ");
        sb.append("Exccom: ").append(getExccom()).append(", ");
        sb.append("Excdom: ").append(getExcdom()).append(", ");
        sb.append("Excmax: ").append(getExcmax()).append(", ");
        sb.append("Excven: ").append(getExcven()).append(", ");
        sb.append("Fecsist: ").append(getFecsist()).append(", ");
        sb.append("Limci: ").append(getLimci()).append(", ");
        sb.append("Limext: ").append(getLimext()).append(", ");
        sb.append("Limite: ").append(getLimite()).append(", ");
        sb.append("Limrem: ").append(getLimrem()).append(", ");
        sb.append("Promanu: ").append(getPromanu()).append(", ");
        sb.append("Prommes: ").append(getPrommes()).append(", ");
        sb.append("Promper: ").append(getPromper()).append(", ");
        sb.append("Saladeu: ").append(getSaladeu()).append(", ");
        sb.append("Saldis: ").append(getSaldis()).append(", ");
        sb.append("Saldist: ").append(getSaldist()).append(", ");
        sb.append("Salextr: ").append(getSalextr()).append(", ");
        sb.append("Salimp: ").append(getSalimp()).append(", ");
        sb.append("Salmism: ").append(getSalmism()).append(", ");
        sb.append("Salpla: ").append(getSalpla()).append(", ");
        sb.append("Salret: ").append(getSalret()).append(", ");
        sb.append("Salval: ").append(getSalval()).append(", ");
        sb.append("Salvouc: ").append(getSalvouc()).append(", ");
        sb.append("Subpro: ").append(getSubpro()).append(", ");
        sb.append("Ultliq: ").append(getUltliq());
        return sb.toString();
    }
    
}
