// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.io.Serializable;

privileged aspect FormatoBGM4027_Roo_Serializable {
    
    declare parents: FormatoBGM4027 implements Serializable;
    
    private static final long FormatoBGM4027.serialVersionUID = 1L;
    
}
