// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import com.bbva.jee.arq.spring.core.host.CuerpoMultiparte;

privileged aspect PeticionTransaccionB402_Roo_JavaBean {
    
    public void PeticionTransaccionB402.setCuerpo(CuerpoMultiparte cuerpo) {
        this.cuerpo = cuerpo;
    }
    
}
