// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM402_Roo_JavaBean {
    
    public String FormatoBGM402.getCcc() {
        return this.ccc;
    }
    
    public void FormatoBGM402.setCcc(String ccc) {
        this.ccc = ccc;
    }
    
    public String FormatoBGM402.getOpcion() {
        return this.opcion;
    }
    
    public void FormatoBGM402.setOpcion(String opcion) {
        this.opcion = opcion;
    }
    
    public String FormatoBGM402.getPapel() {
        return this.papel;
    }
    
    public void FormatoBGM402.setPapel(String papel) {
        this.papel = papel;
    }
    
    public String FormatoBGM402.getLibre() {
        return this.libre;
    }
    
    public void FormatoBGM402.setLibre(String libre) {
        this.libre = libre;
    }
    
}
