// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b000;

import java.lang.String;

privileged aspect FormatoBGM0001_Roo_JavaBean {
    
    public String FormatoBGM0001.getEntidad() {
        return this.entidad;
    }
    
    public void FormatoBGM0001.setEntidad(String entidad) {
        this.entidad = entidad;
    }
    
    public String FormatoBGM0001.getCentro() {
        return this.centro;
    }
    
    public void FormatoBGM0001.setCentro(String centro) {
        this.centro = centro;
    }
    
    public String FormatoBGM0001.getDigitos() {
        return this.digitos;
    }
    
    public void FormatoBGM0001.setDigitos(String digitos) {
        this.digitos = digitos;
    }
    
    public String FormatoBGM0001.getCuenta() {
        return this.cuenta;
    }
    
    public void FormatoBGM0001.setCuenta(String cuenta) {
        this.cuenta = cuenta;
    }
    
    public String FormatoBGM0001.getConcept() {
        return this.concept;
    }
    
    public void FormatoBGM0001.setConcept(String concept) {
        this.concept = concept;
    }
    
}
