// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM4025_Roo_ToString {
    
    public String FormatoBGM4025.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Codtran: ").append(getCodtran()).append(", ");
        sb.append("Desdivi: ").append(getDesdivi()).append(", ");
        sb.append("Fechaca: ").append(getFechaca()).append(", ");
        sb.append("Fechafi: ").append(getFechafi()).append(", ");
        sb.append("Hora: ").append(getHora()).append(", ");
        sb.append("Horafi: ").append(getHorafi()).append(", ");
        sb.append("Litcta: ").append(getLitcta()).append(", ");
        sb.append("Saldodi: ").append(getSaldodi()).append(", ");
        sb.append("Saldoto: ").append(getSaldoto()).append(", ");
        sb.append("Secuenc: ").append(getSecuenc()).append(", ");
        sb.append("Sucursa: ").append(getSucursa()).append(", ");
        sb.append("Termina: ").append(getTermina());
        return sb.toString();
    }
    
}
