// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.proxyservicemppm.dao.model.mppm;

import java.io.Serializable;

privileged aspect FormatoMPPM00E_Roo_Serializable {
    
    declare parents: FormatoMPPM00E implements Serializable;
    
    private static final long FormatoMPPM00E.serialVersionUID = 1L;
    
}
