// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b431;

import java.lang.String;

privileged aspect FormatoBGMLIT1_Roo_JavaBean {
    
    public String FormatoBGMLIT1.getLiteral() {
        return this.literal;
    }
    
    public void FormatoBGMLIT1.setLiteral(String literal) {
        this.literal = literal;
    }
    
}
