// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.Integer;
import java.lang.String;

privileged aspect FormatoBGM402B_Roo_JavaBean {
    
    public String FormatoBGM402B.getEstado() {
        return this.estado;
    }
    
    public void FormatoBGM402B.setEstado(String estado) {
        this.estado = estado;
    }
    
    public String FormatoBGM402B.getCond1() {
        return this.cond1;
    }
    
    public void FormatoBGM402B.setCond1(String cond1) {
        this.cond1 = cond1;
    }
    
    public String FormatoBGM402B.getCancel() {
        return this.cancel;
    }
    
    public void FormatoBGM402B.setCancel(String cancel) {
        this.cancel = cancel;
    }
    
    public Integer FormatoBGM402B.getNumimp() {
        return this.numimp;
    }
    
    public void FormatoBGM402B.setNumimp(Integer numimp) {
        this.numimp = numimp;
    }
    
    public String FormatoBGM402B.getCon107() {
        return this.con107;
    }
    
    public void FormatoBGM402B.setCon107(String con107) {
        this.con107 = con107;
    }
    
    public String FormatoBGM402B.getOfiges() {
        return this.ofiges;
    }
    
    public void FormatoBGM402B.setOfiges(String ofiges) {
        this.ofiges = ofiges;
    }
    
    public String FormatoBGM402B.getUnigest() {
        return this.unigest;
    }
    
    public void FormatoBGM402B.setUnigest(String unigest) {
        this.unigest = unigest;
    }
    
    public String FormatoBGM402B.getFechas() {
        return this.fechas;
    }
    
    public void FormatoBGM402B.setFechas(String fechas) {
        this.fechas = fechas;
    }
    
    public String FormatoBGM402B.getCon105() {
        return this.con105;
    }
    
    public void FormatoBGM402B.setCon105(String con105) {
        this.con105 = con105;
    }
    
    public String FormatoBGM402B.getPuntosp() {
        return this.puntosp;
    }
    
    public void FormatoBGM402B.setPuntosp(String puntosp) {
        this.puntosp = puntosp;
    }
    
    public String FormatoBGM402B.getPuntosn() {
        return this.puntosn;
    }
    
    public void FormatoBGM402B.setPuntosn(String puntosn) {
        this.puntosn = puntosn;
    }
    
    public String FormatoBGM402B.getPuntose() {
        return this.puntose;
    }
    
    public void FormatoBGM402B.setPuntose(String puntose) {
        this.puntose = puntose;
    }
    
    public String FormatoBGM402B.getPuntosm() {
        return this.puntosm;
    }
    
    public void FormatoBGM402B.setPuntosm(String puntosm) {
        this.puntosm = puntosm;
    }
    
    public String FormatoBGM402B.getCon106() {
        return this.con106;
    }
    
    public void FormatoBGM402B.setCon106(String con106) {
        this.con106 = con106;
    }
    
    public String FormatoBGM402B.getTitula() {
        return this.titula;
    }
    
    public void FormatoBGM402B.setTitula(String titula) {
        this.titula = titula;
    }
    
    public String FormatoBGM402B.getNif() {
        return this.nif;
    }
    
    public void FormatoBGM402B.setNif(String nif) {
        this.nif = nif;
    }
    
    public String FormatoBGM402B.getCon108() {
        return this.con108;
    }
    
    public void FormatoBGM402B.setCon108(String con108) {
        this.con108 = con108;
    }
    
    public String FormatoBGM402B.getCorasu() {
        return this.corasu;
    }
    
    public void FormatoBGM402B.setCorasu(String corasu) {
        this.corasu = corasu;
    }
    
    public String FormatoBGM402B.getCon12() {
        return this.con12;
    }
    
    public void FormatoBGM402B.setCon12(String con12) {
        this.con12 = con12;
    }
    
    public String FormatoBGM402B.getLitdis() {
        return this.litdis;
    }
    
    public void FormatoBGM402B.setLitdis(String litdis) {
        this.litdis = litdis;
    }
    
    public String FormatoBGM402B.getCon16() {
        return this.con16;
    }
    
    public void FormatoBGM402B.setCon16(String con16) {
        this.con16 = con16;
    }
    
    public String FormatoBGM402B.getCon20() {
        return this.con20;
    }
    
    public void FormatoBGM402B.setCon20(String con20) {
        this.con20 = con20;
    }
    
    public String FormatoBGM402B.getRegf() {
        return this.regf;
    }
    
    public void FormatoBGM402B.setRegf(String regf) {
        this.regf = regf;
    }
    
    public String FormatoBGM402B.getCon29() {
        return this.con29;
    }
    
    public void FormatoBGM402B.setCon29(String con29) {
        this.con29 = con29;
    }
    
    public String FormatoBGM402B.getSituob() {
        return this.situob;
    }
    
    public void FormatoBGM402B.setSituob(String situob) {
        this.situob = situob;
    }
    
    public String FormatoBGM402B.getCon36() {
        return this.con36;
    }
    
    public void FormatoBGM402B.setCon36(String con36) {
        this.con36 = con36;
    }
    
    public String FormatoBGM402B.getSitusu() {
        return this.situsu;
    }
    
    public void FormatoBGM402B.setSitusu(String situsu) {
        this.situsu = situsu;
    }
    
    public String FormatoBGM402B.getCon37() {
        return this.con37;
    }
    
    public void FormatoBGM402B.setCon37(String con37) {
        this.con37 = con37;
    }
    
    public String FormatoBGM402B.getSituin() {
        return this.situin;
    }
    
    public void FormatoBGM402B.setSituin(String situin) {
        this.situin = situin;
    }
    
    public String FormatoBGM402B.getCon38() {
        return this.con38;
    }
    
    public void FormatoBGM402B.setCon38(String con38) {
        this.con38 = con38;
    }
    
    public String FormatoBGM402B.getTarifa() {
        return this.tarifa;
    }
    
    public void FormatoBGM402B.setTarifa(String tarifa) {
        this.tarifa = tarifa;
    }
    
    public String FormatoBGM402B.getLidiom() {
        return this.lidiom;
    }
    
    public void FormatoBGM402B.setLidiom(String lidiom) {
        this.lidiom = lidiom;
    }
    
    public String FormatoBGM402B.getCon34() {
        return this.con34;
    }
    
    public void FormatoBGM402B.setCon34(String con34) {
        this.con34 = con34;
    }
    
    public String FormatoBGM402B.getSallib() {
        return this.sallib;
    }
    
    public void FormatoBGM402B.setSallib(String sallib) {
        this.sallib = sallib;
    }
    
}
