// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b431;

import java.lang.String;

privileged aspect FormatoBGM4312_Roo_ToString {
    
    public String FormatoBGM4312.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Claset: ").append(getClaset()).append(", ");
        sb.append("Crenvio: ").append(getCrenvio()).append(", ");
        sb.append("Disp: ").append(getDisp()).append(", ");
        sb.append("Estadot: ").append(getEstadot()).append(", ");
        sb.append("Fecalta: ").append(getFecalta()).append(", ");
        sb.append("Fecent: ").append(getFecent()).append(", ");
        sb.append("Prcheq: ").append(getPrcheq()).append(", ");
        sb.append("Solaut: ").append(getSolaut()).append(", ");
        sb.append("Tctaman: ").append(getTctaman()).append(", ");
        sb.append("Total: ").append(getTotal()).append(", ");
        sb.append("Ulcheq: ").append(getUlcheq());
        return sb.toString();
    }
    
}
