// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM4027_Roo_ToString {
    
    public String FormatoBGM4027.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Desci: ").append(getDesci()).append(", ");
        sb.append("Desext: ").append(getDesext()).append(", ");
        sb.append("Desrem: ").append(getDesrem()).append(", ");
        sb.append("Desvou: ").append(getDesvou()).append(", ");
        sb.append("Disci: ").append(getDisci()).append(", ");
        sb.append("Disext: ").append(getDisext()).append(", ");
        sb.append("Disrem: ").append(getDisrem()).append(", ");
        sb.append("Disvou: ").append(getDisvou()).append(", ");
        sb.append("Exccaj: ").append(getExccaj()).append(", ");
        sb.append("Exccom: ").append(getExccom()).append(", ");
        sb.append("Excdom: ").append(getExcdom()).append(", ");
        sb.append("Excmax: ").append(getExcmax()).append(", ");
        sb.append("Excven: ").append(getExcven()).append(", ");
        sb.append("Fecvto: ").append(getFecvto()).append(", ");
        sb.append("Limci: ").append(getLimci()).append(", ");
        sb.append("Limext: ").append(getLimext()).append(", ");
        sb.append("Limrem: ").append(getLimrem()).append(", ");
        sb.append("Limvou: ").append(getLimvou());
        return sb.toString();
    }
    
}
