// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b000;

import java.io.Serializable;

privileged aspect FormatoBGM0001_Roo_Serializable {
    
    declare parents: FormatoBGM0001 implements Serializable;
    
    private static final long FormatoBGM0001.serialVersionUID = 1L;
    
}
