// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;
import java.math.BigDecimal;

privileged aspect FormatoBGM4026_Roo_JavaBean {
    
    public String FormatoBGM4026.getCon05() {
        return this.con05;
    }
    
    public void FormatoBGM4026.setCon05(String con05) {
        this.con05 = con05;
    }
    
    public String FormatoBGM4026.getDepto() {
        return this.depto;
    }
    
    public void FormatoBGM4026.setDepto(String depto) {
        this.depto = depto;
    }
    
    public String FormatoBGM4026.getCon06() {
        return this.con06;
    }
    
    public void FormatoBGM4026.setCon06(String con06) {
        this.con06 = con06;
    }
    
    public String FormatoBGM4026.getCond23() {
        return this.cond23;
    }
    
    public void FormatoBGM4026.setCond23(String cond23) {
        this.cond23 = cond23;
    }
    
    public String FormatoBGM4026.getCond24() {
        return this.cond24;
    }
    
    public void FormatoBGM4026.setCond24(String cond24) {
        this.cond24 = cond24;
    }
    
    public String FormatoBGM4026.getCond31() {
        return this.cond31;
    }
    
    public void FormatoBGM4026.setCond31(String cond31) {
        this.cond31 = cond31;
    }
    
    public String FormatoBGM4026.getCuotimp() {
        return this.cuotimp;
    }
    
    public void FormatoBGM4026.setCuotimp(String cuotimp) {
        this.cuotimp = cuotimp;
    }
    
    public String FormatoBGM4026.getLitahoi() {
        return this.litahoi;
    }
    
    public void FormatoBGM4026.setLitahoi(String litahoi) {
        this.litahoi = litahoi;
    }
    
    public String FormatoBGM4026.getSalahoi() {
        return this.salahoi;
    }
    
    public void FormatoBGM4026.setSalahoi(String salahoi) {
        this.salahoi = salahoi;
    }
    
}
