// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;
import java.util.Date;

privileged aspect FormatoBGM4027_Roo_JavaBean {
    
    public Date FormatoBGM4027.getFecvto() {
        return this.fecvto;
    }
    
    public void FormatoBGM4027.setFecvto(Date fecvto) {
        this.fecvto = fecvto;
    }
    
    public String FormatoBGM4027.getLimvou() {
        return this.limvou;
    }
    
    public void FormatoBGM4027.setLimvou(String limvou) {
        this.limvou = limvou;
    }
    
    public String FormatoBGM4027.getDisvou() {
        return this.disvou;
    }
    
    public void FormatoBGM4027.setDisvou(String disvou) {
        this.disvou = disvou;
    }
    
    public String FormatoBGM4027.getLimrem() {
        return this.limrem;
    }
    
    public void FormatoBGM4027.setLimrem(String limrem) {
        this.limrem = limrem;
    }
    
    public String FormatoBGM4027.getDisrem() {
        return this.disrem;
    }
    
    public void FormatoBGM4027.setDisrem(String disrem) {
        this.disrem = disrem;
    }
    
    public String FormatoBGM4027.getLimci() {
        return this.limci;
    }
    
    public void FormatoBGM4027.setLimci(String limci) {
        this.limci = limci;
    }
    
    public String FormatoBGM4027.getDisci() {
        return this.disci;
    }
    
    public void FormatoBGM4027.setDisci(String disci) {
        this.disci = disci;
    }
    
    public String FormatoBGM4027.getLimext() {
        return this.limext;
    }
    
    public void FormatoBGM4027.setLimext(String limext) {
        this.limext = limext;
    }
    
    public String FormatoBGM4027.getDisext() {
        return this.disext;
    }
    
    public void FormatoBGM4027.setDisext(String disext) {
        this.disext = disext;
    }
    
    public String FormatoBGM4027.getDesvou() {
        return this.desvou;
    }
    
    public void FormatoBGM4027.setDesvou(String desvou) {
        this.desvou = desvou;
    }
    
    public String FormatoBGM4027.getDesrem() {
        return this.desrem;
    }
    
    public void FormatoBGM4027.setDesrem(String desrem) {
        this.desrem = desrem;
    }
    
    public String FormatoBGM4027.getDesci() {
        return this.desci;
    }
    
    public void FormatoBGM4027.setDesci(String desci) {
        this.desci = desci;
    }
    
    public String FormatoBGM4027.getDesext() {
        return this.desext;
    }
    
    public void FormatoBGM4027.setDesext(String desext) {
        this.desext = desext;
    }
    
    public String FormatoBGM4027.getExcmax() {
        return this.excmax;
    }
    
    public void FormatoBGM4027.setExcmax(String excmax) {
        this.excmax = excmax;
    }
    
    public String FormatoBGM4027.getExcven() {
        return this.excven;
    }
    
    public void FormatoBGM4027.setExcven(String excven) {
        this.excven = excven;
    }
    
    public String FormatoBGM4027.getExcdom() {
        return this.excdom;
    }
    
    public void FormatoBGM4027.setExcdom(String excdom) {
        this.excdom = excdom;
    }
    
    public String FormatoBGM4027.getExccaj() {
        return this.exccaj;
    }
    
    public void FormatoBGM4027.setExccaj(String exccaj) {
        this.exccaj = exccaj;
    }
    
    public String FormatoBGM4027.getExccom() {
        return this.exccom;
    }
    
    public void FormatoBGM4027.setExccom(String exccom) {
        this.exccom = exccom;
    }
    
}
