// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b000;

import java.lang.String;

privileged aspect FormatoBGM000_Roo_ToString {
    
    public String FormatoBGM000.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Concept: ").append(getConcept()).append(", ");
        sb.append("Entcto: ").append(getEntcto()).append(", ");
        sb.append("Libre: ").append(getLibre()).append(", ");
        sb.append("Papel: ").append(getPapel()).append(", ");
        sb.append("Product: ").append(getProduct());
        return sb.toString();
    }
    
}
