// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;

privileged aspect FormatoBGM402B_Roo_ToString {
    
    public String FormatoBGM402B.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Cancel: ").append(getCancel()).append(", ");
        sb.append("Con105: ").append(getCon105()).append(", ");
        sb.append("Con106: ").append(getCon106()).append(", ");
        sb.append("Con107: ").append(getCon107()).append(", ");
        sb.append("Con108: ").append(getCon108()).append(", ");
        sb.append("Con12: ").append(getCon12()).append(", ");
        sb.append("Con16: ").append(getCon16()).append(", ");
        sb.append("Con20: ").append(getCon20()).append(", ");
        sb.append("Con29: ").append(getCon29()).append(", ");
        sb.append("Con34: ").append(getCon34()).append(", ");
        sb.append("Con36: ").append(getCon36()).append(", ");
        sb.append("Con37: ").append(getCon37()).append(", ");
        sb.append("Con38: ").append(getCon38()).append(", ");
        sb.append("Cond1: ").append(getCond1()).append(", ");
        sb.append("Corasu: ").append(getCorasu()).append(", ");
        sb.append("Estado: ").append(getEstado()).append(", ");
        sb.append("Fechas: ").append(getFechas()).append(", ");
        sb.append("Lidiom: ").append(getLidiom()).append(", ");
        sb.append("Litdis: ").append(getLitdis()).append(", ");
        sb.append("Nif: ").append(getNif()).append(", ");
        sb.append("Numimp: ").append(getNumimp()).append(", ");
        sb.append("Ofiges: ").append(getOfiges()).append(", ");
        sb.append("Puntose: ").append(getPuntose()).append(", ");
        sb.append("Puntosm: ").append(getPuntosm()).append(", ");
        sb.append("Puntosn: ").append(getPuntosn()).append(", ");
        sb.append("Puntosp: ").append(getPuntosp()).append(", ");
        sb.append("Regf: ").append(getRegf()).append(", ");
        sb.append("Sallib: ").append(getSallib()).append(", ");
        sb.append("Situin: ").append(getSituin()).append(", ");
        sb.append("Situob: ").append(getSituob()).append(", ");
        sb.append("Situsu: ").append(getSitusu()).append(", ");
        sb.append("Tarifa: ").append(getTarifa()).append(", ");
        sb.append("Titula: ").append(getTitula()).append(", ");
        sb.append("Unigest: ").append(getUnigest());
        return sb.toString();
    }
    
}
