// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accountsv02.dao.model.b402;

import java.lang.String;
import java.util.Date;

privileged aspect FormatoBGM402A_Roo_JavaBean {
    
    public Date FormatoBGM402A.getFecsist() {
        return this.fecsist;
    }
    
    public void FormatoBGM402A.setFecsist(Date fecsist) {
        this.fecsist = fecsist;
    }
    
    public String FormatoBGM402A.getCcc() {
        return this.ccc;
    }
    
    public void FormatoBGM402A.setCcc(String ccc) {
        this.ccc = ccc;
    }
    
    public String FormatoBGM402A.getClaveb() {
        return this.claveb;
    }
    
    public void FormatoBGM402A.setClaveb(String claveb) {
        this.claveb = claveb;
    }
    
    public String FormatoBGM402A.getCtacen() {
        return this.ctacen;
    }
    
    public void FormatoBGM402A.setCtacen(String ctacen) {
        this.ctacen = ctacen;
    }
    
    public String FormatoBGM402A.getConcc() {
        return this.concc;
    }
    
    public void FormatoBGM402A.setConcc(String concc) {
        this.concc = concc;
    }
    
    public String FormatoBGM402A.getSubpro() {
        return this.subpro;
    }
    
    public void FormatoBGM402A.setSubpro(String subpro) {
        this.subpro = subpro;
    }
    
    public String FormatoBGM402A.getCccaso() {
        return this.cccaso;
    }
    
    public void FormatoBGM402A.setCccaso(String cccaso) {
        this.cccaso = cccaso;
    }
    
    public String FormatoBGM402A.getDivisa() {
        return this.divisa;
    }
    
    public void FormatoBGM402A.setDivisa(String divisa) {
        this.divisa = divisa;
    }
    
    public String FormatoBGM402A.getSaldis() {
        return this.saldis;
    }
    
    public void FormatoBGM402A.setSaldis(String saldis) {
        this.saldis = saldis;
    }
    
    public String FormatoBGM402A.getDispon() {
        return this.dispon;
    }
    
    public void FormatoBGM402A.setDispon(String dispon) {
        this.dispon = dispon;
    }
    
    public String FormatoBGM402A.getLimite() {
        return this.limite;
    }
    
    public void FormatoBGM402A.setLimite(String limite) {
        this.limite = limite;
    }
    
    public String FormatoBGM402A.getExcmax() {
        return this.excmax;
    }
    
    public void FormatoBGM402A.setExcmax(String excmax) {
        this.excmax = excmax;
    }
    
    public String FormatoBGM402A.getExcven() {
        return this.excven;
    }
    
    public void FormatoBGM402A.setExcven(String excven) {
        this.excven = excven;
    }
    
    public String FormatoBGM402A.getExcdom() {
        return this.excdom;
    }
    
    public void FormatoBGM402A.setExcdom(String excdom) {
        this.excdom = excdom;
    }
    
    public String FormatoBGM402A.getExccaj() {
        return this.exccaj;
    }
    
    public void FormatoBGM402A.setExccaj(String exccaj) {
        this.exccaj = exccaj;
    }
    
    public String FormatoBGM402A.getExccom() {
        return this.exccom;
    }
    
    public void FormatoBGM402A.setExccom(String exccom) {
        this.exccom = exccom;
    }
    
    public String FormatoBGM402A.getSalret() {
        return this.salret;
    }
    
    public void FormatoBGM402A.setSalret(String salret) {
        this.salret = salret;
    }
    
    public String FormatoBGM402A.getSalimp() {
        return this.salimp;
    }
    
    public void FormatoBGM402A.setSalimp(String salimp) {
        this.salimp = salimp;
    }
    
    public String FormatoBGM402A.getCon1() {
        return this.con1;
    }
    
    public void FormatoBGM402A.setCon1(String con1) {
        this.con1 = con1;
    }
    
    public String FormatoBGM402A.getCon2() {
        return this.con2;
    }
    
    public void FormatoBGM402A.setCon2(String con2) {
        this.con2 = con2;
    }
    
    public String FormatoBGM402A.getCon3() {
        return this.con3;
    }
    
    public void FormatoBGM402A.setCon3(String con3) {
        this.con3 = con3;
    }
    
    public String FormatoBGM402A.getCon4() {
        return this.con4;
    }
    
    public void FormatoBGM402A.setCon4(String con4) {
        this.con4 = con4;
    }
    
    public String FormatoBGM402A.getCon5() {
        return this.con5;
    }
    
    public void FormatoBGM402A.setCon5(String con5) {
        this.con5 = con5;
    }
    
    public String FormatoBGM402A.getCon6() {
        return this.con6;
    }
    
    public void FormatoBGM402A.setCon6(String con6) {
        this.con6 = con6;
    }
    
    public String FormatoBGM402A.getCon7() {
        return this.con7;
    }
    
    public void FormatoBGM402A.setCon7(String con7) {
        this.con7 = con7;
    }
    
    public String FormatoBGM402A.getCon8() {
        return this.con8;
    }
    
    public void FormatoBGM402A.setCon8(String con8) {
        this.con8 = con8;
    }
    
    public String FormatoBGM402A.getCon9() {
        return this.con9;
    }
    
    public void FormatoBGM402A.setCon9(String con9) {
        this.con9 = con9;
    }
    
    public String FormatoBGM402A.getUltliq() {
        return this.ultliq;
    }
    
    public void FormatoBGM402A.setUltliq(String ultliq) {
        this.ultliq = ultliq;
    }
    
    public String FormatoBGM402A.getSalval() {
        return this.salval;
    }
    
    public void FormatoBGM402A.setSalval(String salval) {
        this.salval = salval;
    }
    
    public String FormatoBGM402A.getPromanu() {
        return this.promanu;
    }
    
    public void FormatoBGM402A.setPromanu(String promanu) {
        this.promanu = promanu;
    }
    
    public String FormatoBGM402A.getPrommes() {
        return this.prommes;
    }
    
    public void FormatoBGM402A.setPrommes(String prommes) {
        this.prommes = prommes;
    }
    
    public String FormatoBGM402A.getPromper() {
        return this.promper;
    }
    
    public void FormatoBGM402A.setPromper(String promper) {
        this.promper = promper;
    }
    
    public String FormatoBGM402A.getCon44() {
        return this.con44;
    }
    
    public void FormatoBGM402A.setCon44(String con44) {
        this.con44 = con44;
    }
    
    public String FormatoBGM402A.getSaladeu() {
        return this.saladeu;
    }
    
    public void FormatoBGM402A.setSaladeu(String saladeu) {
        this.saladeu = saladeu;
    }
    
    public String FormatoBGM402A.getSalmism() {
        return this.salmism;
    }
    
    public void FormatoBGM402A.setSalmism(String salmism) {
        this.salmism = salmism;
    }
    
    public String FormatoBGM402A.getSaldist() {
        return this.saldist;
    }
    
    public void FormatoBGM402A.setSaldist(String saldist) {
        this.saldist = saldist;
    }
    
    public String FormatoBGM402A.getSalextr() {
        return this.salextr;
    }
    
    public void FormatoBGM402A.setSalextr(String salextr) {
        this.salextr = salextr;
    }
    
    public String FormatoBGM402A.getSalvouc() {
        return this.salvouc;
    }
    
    public void FormatoBGM402A.setSalvouc(String salvouc) {
        this.salvouc = salvouc;
    }
    
    public String FormatoBGM402A.getConsal() {
        return this.consal;
    }
    
    public void FormatoBGM402A.setConsal(String consal) {
        this.consal = consal;
    }
    
    public String FormatoBGM402A.getLimci() {
        return this.limci;
    }
    
    public void FormatoBGM402A.setLimci(String limci) {
        this.limci = limci;
    }
    
    public String FormatoBGM402A.getDisci() {
        return this.disci;
    }
    
    public void FormatoBGM402A.setDisci(String disci) {
        this.disci = disci;
    }
    
    public String FormatoBGM402A.getLimrem() {
        return this.limrem;
    }
    
    public void FormatoBGM402A.setLimrem(String limrem) {
        this.limrem = limrem;
    }
    
    public String FormatoBGM402A.getDisrem() {
        return this.disrem;
    }
    
    public void FormatoBGM402A.setDisrem(String disrem) {
        this.disrem = disrem;
    }
    
    public String FormatoBGM402A.getCon109() {
        return this.con109;
    }
    
    public void FormatoBGM402A.setCon109(String con109) {
        this.con109 = con109;
    }
    
    public String FormatoBGM402A.getCon110() {
        return this.con110;
    }
    
    public void FormatoBGM402A.setCon110(String con110) {
        this.con110 = con110;
    }
    
    public String FormatoBGM402A.getCon111() {
        return this.con111;
    }
    
    public void FormatoBGM402A.setCon111(String con111) {
        this.con111 = con111;
    }
    
    public String FormatoBGM402A.getCon112() {
        return this.con112;
    }
    
    public void FormatoBGM402A.setCon112(String con112) {
        this.con112 = con112;
    }
    
    public String FormatoBGM402A.getCon10() {
        return this.con10;
    }
    
    public void FormatoBGM402A.setCon10(String con10) {
        this.con10 = con10;
    }
    
    public String FormatoBGM402A.getLimext() {
        return this.limext;
    }
    
    public void FormatoBGM402A.setLimext(String limext) {
        this.limext = limext;
    }
    
    public String FormatoBGM402A.getDisext() {
        return this.disext;
    }
    
    public void FormatoBGM402A.setDisext(String disext) {
        this.disext = disext;
    }
    
    public String FormatoBGM402A.getCon113() {
        return this.con113;
    }
    
    public void FormatoBGM402A.setCon113(String con113) {
        this.con113 = con113;
    }
    
    public String FormatoBGM402A.getCon114() {
        return this.con114;
    }
    
    public void FormatoBGM402A.setCon114(String con114) {
        this.con114 = con114;
    }
    
    public String FormatoBGM402A.getSalpla() {
        return this.salpla;
    }
    
    public void FormatoBGM402A.setSalpla(String salpla) {
        this.salpla = salpla;
    }
    
    public String FormatoBGM402A.getConlp() {
        return this.conlp;
    }
    
    public void FormatoBGM402A.setConlp(String conlp) {
        this.conlp = conlp;
    }
    
}
